// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mochi.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mochi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MochiDbContext))]
    partial class MochiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mochi.Domain.Collection.AnalyticsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("browser");

                    b.Property<string>("Campaign")
                        .HasColumnType("text")
                        .HasColumnName("campaign");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<short>("DeviceClass")
                        .HasColumnType("smallint")
                        .HasColumnName("device_class");

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("os");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ReferrerDomain")
                        .HasColumnType("text")
                        .HasColumnName("referrer_domain");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long>("Visitor")
                        .HasColumnType("bigint")
                        .HasColumnName("visitor_hash");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "OccurredAt");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Mochi.Domain.Goals.Goal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("Mochi.Domain.Sites.Site", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("Retention")
                        .HasColumnType("smallint")
                        .HasColumnName("retention");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Mochi.Infrastructure.Persistence.DeviceRow", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short>("DeviceClass")
                        .HasColumnType("smallint")
                        .HasColumnName("device_class");

                    b.Property<string>("Browser")
                        .HasColumnType("text")
                        .HasColumnName("browser");

                    b.Property<string>("Os")
                        .HasColumnType("text")
                        .HasColumnName("os");

                    b.Property<int>("Visitors")
                        .HasColumnType("integer")
                        .HasColumnName("visitors");

                    b.HasKey("SiteId", "Date", "DeviceClass", "Browser", "Os");

                    b.ToTable("daily_devices", (string)null);
                });

            modelBuilder.Entity("Mochi.Infrastructure.Persistence.EventRow", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("integer")
                        .HasColumnName("unique_visitors");

                    b.HasKey("SiteId", "Date", "EventName", "Path", "Channel");

                    b.ToTable("daily_events", (string)null);
                });

            modelBuilder.Entity("Mochi.Infrastructure.Persistence.GeoRow", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<int>("Visitors")
                        .HasColumnType("integer")
                        .HasColumnName("visitors");

                    b.HasKey("SiteId", "Date", "Country");

                    b.ToTable("daily_geo", (string)null);
                });

            modelBuilder.Entity("Mochi.Infrastructure.Persistence.PageRow", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("BouncedSessions")
                        .HasColumnType("integer")
                        .HasColumnName("bounced_sessions");

                    b.Property<int>("Entries")
                        .HasColumnType("integer")
                        .HasColumnName("entries");

                    b.Property<int>("Exits")
                        .HasColumnType("integer")
                        .HasColumnName("exits");

                    b.Property<int>("Pageviews")
                        .HasColumnType("integer")
                        .HasColumnName("pageviews");

                    b.Property<long>("TotalDurationSec")
                        .HasColumnType("bigint")
                        .HasColumnName("total_duration_sec");

                    b.Property<int>("Visitors")
                        .HasColumnType("integer")
                        .HasColumnName("visitors");

                    b.HasKey("SiteId", "Date", "Path");

                    b.ToTable("daily_pages", (string)null);
                });

            modelBuilder.Entity("Mochi.Infrastructure.Persistence.SiteStatsRow", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("BouncedSessions")
                        .HasColumnType("integer")
                        .HasColumnName("bounced_sessions");

                    b.Property<int>("Pageviews")
                        .HasColumnType("integer")
                        .HasColumnName("pageviews");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer")
                        .HasColumnName("sessions");

                    b.Property<long>("TotalSessionDurationSec")
                        .HasColumnType("bigint")
                        .HasColumnName("total_session_duration_sec");

                    b.Property<int>("Visitors")
                        .HasColumnType("integer")
                        .HasColumnName("visitors");

                    b.HasKey("SiteId", "Date");

                    b.ToTable("daily_site_stats", (string)null);
                });

            modelBuilder.Entity("Mochi.Infrastructure.Persistence.SourceRow", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<string>("ReferrerDomain")
                        .HasColumnType("text")
                        .HasColumnName("referrer_domain");

                    b.Property<string>("Campaign")
                        .HasColumnType("text")
                        .HasColumnName("campaign");

                    b.Property<int>("BouncedSessions")
                        .HasColumnType("integer")
                        .HasColumnName("bounced_sessions");

                    b.Property<int>("Pageviews")
                        .HasColumnType("integer")
                        .HasColumnName("pageviews");

                    b.Property<int>("Visitors")
                        .HasColumnType("integer")
                        .HasColumnName("visitors");

                    b.HasKey("SiteId", "Date", "Channel", "ReferrerDomain", "Campaign");

                    b.ToTable("daily_sources", (string)null);
                });

            modelBuilder.Entity("Mochi.Domain.Collection.AnalyticsEvent", b =>
                {
                    b.HasOne("Mochi.Domain.Sites.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mochi.Domain.Goals.Goal", b =>
                {
                    b.HasOne("Mochi.Domain.Sites.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
